; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:light]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = 
	me-no-dev/ESPAsyncWebServer@^3.6.0
	;h2zero/NimBLE-Arduino
build_src_filter =
	+<**/light_code.cpp>
	-<**/controller_code.cpp>

[env:controller]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = 
	me-no-dev/ESPAsyncWebServer@^3.6.0
	;h2zero/NimBLE-Arduino
build_src_filter =
	-<**/light_code.cpp>
	+<**/controller_code.cpp>
